# Generated by Django 4.2.2 on 2023-07-07 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_link_pseudo_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='pseudo_link',
        ),
    ]
