# Generated by Django 4.2.2 on 2023-07-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_link_pseudo_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='pseudo_link',
            field=models.SlugField(default='', verbose_name='Псевдоним ссылки'),
            preserve_default=False,
        ),
    ]
