# Generated by Django 4.2.2 on 2023-07-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_link_pseudo_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='pseudo_link',
            field=models.SlugField(unique=True, verbose_name='Псевдоним ссылки'),
        ),
    ]
